/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/checklists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a single checklist */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Checklist"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Updates a checklist */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Checklist information */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistForm"];
                };
            };
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /** Deletes a checklist */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Partially updates a checklist */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            /** @description Checklist information */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistForm"];
                };
            };
            responses: {
                /** @description Ok */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/checklists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a list of checklists */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description An array of checklists */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Checklist"][];
                    };
                };
            };
        };
        put?: never;
        /** Creates a new checklist */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Checklist information */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChecklistForm"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChecklistForm: {
            name?: string;
            /** Format: date-time */
            created?: string;
            /** Format: date-time */
            updated?: string;
            style?: components["schemas"]["ChecklistStyle"];
            pageSize?: components["schemas"]["PageSize"];
            pageOrientation?: components["schemas"]["PageOrientation"];
            columns?: number;
            fontSize?: number;
            borderThickness?: components["schemas"]["BorderThickness"];
            fontFamily?: string;
            checklistItems?: (components["schemas"]["SubChecklist"] | components["schemas"]["SectionTitle"] | components["schemas"]["TextBox"])[];
        };
        Checklist: components["schemas"]["ChecklistForm"] & {
            /** Format: uuid */
            id?: string;
        };
        /** @enum {string} */
        PageSize: "A4" | "A5" | "Letter" | "HalfLetter";
        /** @enum {string} */
        PageOrientation: "Portrait" | "Landscape";
        /** @enum {string} */
        ChecklistStyle: "Dots" | "Line" | "MidDots" | "Dashed" | "Table";
        /** @enum {number} */
        BorderThickness: 0 | 1 | 2 | 4;
        SubChecklistForm: {
            /** Format: uuid */
            checklistId?: string;
            title?: string;
            color?: string;
            items?: (components["schemas"]["SubChecklistItemCheckItem"] | components["schemas"]["SubChecklistItemPrecondition"] | components["schemas"]["SubChecklistItemPostcondition"] | components["schemas"]["SubChecklistItemSubtitle"])[];
            type?: components["schemas"]["ChecklistItemType"];
        };
        SubChecklist: components["schemas"]["SubChecklistForm"] & {
            /** Format: uuid */
            id?: string;
        };
        SectionTitleForm: {
            /** Format: uuid */
            checklistId?: string;
            text?: string;
            color?: string;
            type?: components["schemas"]["ChecklistItemType"];
        };
        SectionTitle: components["schemas"]["SectionTitleForm"] & {
            /** Format: uuid */
            id?: string;
        };
        TextBoxForm: {
            /** Format: uuid */
            checklistId?: string;
            text?: string;
            color?: string;
            type?: components["schemas"]["ChecklistItemType"];
        };
        TextBox: components["schemas"]["TextBoxForm"] & {
            /** Format: uuid */
            id?: string;
        };
        ColumnBreakForm: {
            /** Format: uuid */
            checklistId?: string;
            type?: components["schemas"]["ChecklistItemType"];
        };
        ColumnBreak: components["schemas"]["ColumnBreakForm"] & {
            /** Format: uuid */
            id?: string;
        };
        PageBreakForm: {
            /** Format: uuid */
            checklistId?: string;
            type?: components["schemas"]["ChecklistItemType"];
        };
        PageBreak: components["schemas"]["PageBreakForm"] & {
            /** Format: uuid */
            id?: string;
        };
        /** @enum {string} */
        ChecklistItemType: "SubChecklist" | "SectionTitle" | "TextBox" | "ColumnBreak" | "PageBreak";
        SubChecklistItemCheckItemForm: {
            /** Format: uuid */
            subChecklistId?: string;
            item?: string;
            action?: string;
            type?: components["schemas"]["SubChecklistItemType"];
        };
        SubChecklistItemCheckItem: components["schemas"]["SubChecklistItemCheckItemForm"] & {
            /** Format: uuid */
            id?: string;
        };
        SubChecklistItemPreconditionForm: {
            /** Format: uuid */
            subChecklistId?: string;
            text?: string;
            type?: components["schemas"]["SubChecklistItemType"];
        };
        SubChecklistItemPrecondition: components["schemas"]["SubChecklistItemPreconditionForm"] & {
            /** Format: uuid */
            id?: string;
        };
        SubChecklistItemPostconditionForm: {
            /** Format: uuid */
            subChecklistId?: string;
            text?: string;
            type?: components["schemas"]["SubChecklistItemType"];
        };
        SubChecklistItemPostcondition: components["schemas"]["SubChecklistItemPostconditionForm"] & {
            /** Format: uuid */
            id?: string;
        };
        SubChecklistItemSubtitleForm: {
            /** Format: uuid */
            subChecklistId?: string;
            text?: string;
            type?: components["schemas"]["SubChecklistItemType"];
        };
        SubChecklistItemSubtitle: components["schemas"]["SubChecklistItemSubtitleForm"] & {
            /** Format: uuid */
            id?: string;
        };
        /** @enum {string} */
        SubChecklistItemType: "CheckItem" | "Precondition" | "Postcondition" | "Subtitle";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
