openapi: 3.0.3
info:
  title: Checklistix Auth API
  description: Checklistix Auth API
  version: 1.0.0
servers:
  - url: 'https://localhost:9090'
    description: Development server
tags:
  - name: Checklists
paths:
  /sign-up:
    post:
      tags:
        - Auth
      summary: Sign up
      operationId: signUp
      requestBody:
        description: User information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthForm'
      responses:
        '201':
          description: Created
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /sign-in:
    post:
      tags:
        - Auth
      summary: Sign in
      operationId: signIn
      requestBody:
        description: User information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthForm'
      responses:
        '200':
          description: Ok
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /sign-out:
    post:
      tags:
        - Auth
      summary: Sign out
      operationId: signOut
      responses:
        '204':
          description: No content
        '400':
          description: Bad request
        '500':
          description: Internal server error

components:
  schemas:
    AuthForm:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
        rememberMe:
          type: boolean
          default: false
