//go:build go1.22

// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BorderThickness.
const (
	N0 BorderThickness = 0
	N1 BorderThickness = 1
	N2 BorderThickness = 2
	N4 BorderThickness = 4
)

// Defines values for ChecklistItemType.
const (
	ChecklistItemTypeColumnBreak  ChecklistItemType = "ColumnBreak"
	ChecklistItemTypePageBreak    ChecklistItemType = "PageBreak"
	ChecklistItemTypeSectionTitle ChecklistItemType = "SectionTitle"
	ChecklistItemTypeSubChecklist ChecklistItemType = "SubChecklist"
	ChecklistItemTypeTextBox      ChecklistItemType = "TextBox"
)

// Defines values for ChecklistStyle.
const (
	Dashed  ChecklistStyle = "Dashed"
	Dots    ChecklistStyle = "Dots"
	Line    ChecklistStyle = "Line"
	MidDots ChecklistStyle = "MidDots"
	Table   ChecklistStyle = "Table"
)

// Defines values for PageOrientation.
const (
	Landscape PageOrientation = "Landscape"
	Portrait  PageOrientation = "Portrait"
)

// Defines values for PageSize.
const (
	A4         PageSize = "A4"
	A5         PageSize = "A5"
	HalfLetter PageSize = "HalfLetter"
	Letter     PageSize = "Letter"
)

// Defines values for SubChecklistItemType.
const (
	CheckItem     SubChecklistItemType = "CheckItem"
	Postcondition SubChecklistItemType = "Postcondition"
	Precondition  SubChecklistItemType = "Precondition"
	Subtitle      SubChecklistItemType = "Subtitle"
)

// BorderThickness defines model for BorderThickness.
type BorderThickness float32

// Checklist defines model for Checklist.
type Checklist struct {
	BorderThickness BorderThickness                 `json:"borderThickness,omitempty"`
	ChecklistItems  []Checklist_ChecklistItems_Item `json:"checklistItems,omitempty"`
	Columns         int                             `json:"columns,omitempty"`
	Created         time.Time                       `json:"created,omitempty"`
	FontFamily      string                          `json:"fontFamily,omitempty"`
	FontSize        int                             `json:"fontSize,omitempty"`
	Id              openapi_types.UUID              `json:"id,omitempty"`
	Name            string                          `json:"name,omitempty"`
	PageOrientation PageOrientation                 `json:"pageOrientation,omitempty"`
	PageSize        PageSize                        `json:"pageSize,omitempty"`
	Style           ChecklistStyle                  `json:"style,omitempty"`
	Updated         time.Time                       `json:"updated,omitempty"`
}

// Checklist_ChecklistItems_Item defines model for Checklist.checklistItems.Item.
type Checklist_ChecklistItems_Item struct {
	union json.RawMessage
}

// ChecklistForm defines model for ChecklistForm.
type ChecklistForm struct {
	BorderThickness BorderThickness                     `json:"borderThickness,omitempty"`
	ChecklistItems  []ChecklistForm_ChecklistItems_Item `json:"checklistItems,omitempty"`
	Columns         int                                 `json:"columns,omitempty"`
	Created         time.Time                           `json:"created,omitempty"`
	FontFamily      string                              `json:"fontFamily,omitempty"`
	FontSize        int                                 `json:"fontSize,omitempty"`
	Name            string                              `json:"name,omitempty"`
	PageOrientation PageOrientation                     `json:"pageOrientation,omitempty"`
	PageSize        PageSize                            `json:"pageSize,omitempty"`
	Style           ChecklistStyle                      `json:"style,omitempty"`
	Updated         time.Time                           `json:"updated,omitempty"`
}

// ChecklistForm_ChecklistItems_Item defines model for ChecklistForm.checklistItems.Item.
type ChecklistForm_ChecklistItems_Item struct {
	union json.RawMessage
}

// ChecklistItemType defines model for ChecklistItemType.
type ChecklistItemType string

// ChecklistStyle defines model for ChecklistStyle.
type ChecklistStyle string

// PageOrientation defines model for PageOrientation.
type PageOrientation string

// PageSize defines model for PageSize.
type PageSize string

// SectionTitle defines model for SectionTitle.
type SectionTitle struct {
	ChecklistId openapi_types.UUID `json:"checklistId,omitempty"`
	Color       string             `json:"color,omitempty"`
	Id          openapi_types.UUID `json:"id,omitempty"`
	Text        string             `json:"text,omitempty"`
	Type        ChecklistItemType  `json:"type,omitempty"`
}

// SectionTitleForm defines model for SectionTitleForm.
type SectionTitleForm struct {
	ChecklistId openapi_types.UUID `json:"checklistId,omitempty"`
	Color       string             `json:"color,omitempty"`
	Text        string             `json:"text,omitempty"`
	Type        ChecklistItemType  `json:"type,omitempty"`
}

// SubChecklist defines model for SubChecklist.
type SubChecklist struct {
	ChecklistId openapi_types.UUID        `json:"checklistId,omitempty"`
	Color       string                    `json:"color,omitempty"`
	Id          openapi_types.UUID        `json:"id,omitempty"`
	Items       []SubChecklist_Items_Item `json:"items,omitempty"`
	Title       string                    `json:"title,omitempty"`
	Type        ChecklistItemType         `json:"type,omitempty"`
}

// SubChecklist_Items_Item defines model for SubChecklist.items.Item.
type SubChecklist_Items_Item struct {
	union json.RawMessage
}

// SubChecklistForm defines model for SubChecklistForm.
type SubChecklistForm struct {
	ChecklistId openapi_types.UUID            `json:"checklistId,omitempty"`
	Color       string                        `json:"color,omitempty"`
	Items       []SubChecklistForm_Items_Item `json:"items,omitempty"`
	Title       string                        `json:"title,omitempty"`
	Type        ChecklistItemType             `json:"type,omitempty"`
}

// SubChecklistForm_Items_Item defines model for SubChecklistForm.items.Item.
type SubChecklistForm_Items_Item struct {
	union json.RawMessage
}

// SubChecklistItemCheckItem defines model for SubChecklistItemCheckItem.
type SubChecklistItemCheckItem struct {
	Action         string               `json:"action,omitempty"`
	Id             openapi_types.UUID   `json:"id,omitempty"`
	Item           string               `json:"item,omitempty"`
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemCheckItemForm defines model for SubChecklistItemCheckItemForm.
type SubChecklistItemCheckItemForm struct {
	Action         string               `json:"action,omitempty"`
	Item           string               `json:"item,omitempty"`
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemPostcondition defines model for SubChecklistItemPostcondition.
type SubChecklistItemPostcondition struct {
	Id             openapi_types.UUID   `json:"id,omitempty"`
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemPostconditionForm defines model for SubChecklistItemPostconditionForm.
type SubChecklistItemPostconditionForm struct {
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemPrecondition defines model for SubChecklistItemPrecondition.
type SubChecklistItemPrecondition struct {
	Id             openapi_types.UUID   `json:"id,omitempty"`
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemPreconditionForm defines model for SubChecklistItemPreconditionForm.
type SubChecklistItemPreconditionForm struct {
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemSubtitle defines model for SubChecklistItemSubtitle.
type SubChecklistItemSubtitle struct {
	Id             openapi_types.UUID   `json:"id,omitempty"`
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemSubtitleForm defines model for SubChecklistItemSubtitleForm.
type SubChecklistItemSubtitleForm struct {
	SubChecklistId openapi_types.UUID   `json:"subChecklistId,omitempty"`
	Text           string               `json:"text,omitempty"`
	Type           SubChecklistItemType `json:"type,omitempty"`
}

// SubChecklistItemType defines model for SubChecklistItemType.
type SubChecklistItemType string

// TextBox defines model for TextBox.
type TextBox struct {
	ChecklistId openapi_types.UUID `json:"checklistId,omitempty"`
	Color       string             `json:"color,omitempty"`
	Id          openapi_types.UUID `json:"id,omitempty"`
	Text        string             `json:"text,omitempty"`
	Type        ChecklistItemType  `json:"type,omitempty"`
}

// TextBoxForm defines model for TextBoxForm.
type TextBoxForm struct {
	ChecklistId openapi_types.UUID `json:"checklistId,omitempty"`
	Color       string             `json:"color,omitempty"`
	Text        string             `json:"text,omitempty"`
	Type        ChecklistItemType  `json:"type,omitempty"`
}

// PostChecklistsJSONRequestBody defines body for PostChecklists for application/json ContentType.
type PostChecklistsJSONRequestBody = ChecklistForm

// PatchChecklistsIdJSONRequestBody defines body for PatchChecklistsId for application/json ContentType.
type PatchChecklistsIdJSONRequestBody = ChecklistForm

// PutChecklistsIdJSONRequestBody defines body for PutChecklistsId for application/json ContentType.
type PutChecklistsIdJSONRequestBody = ChecklistForm

// AsSubChecklist returns the union data inside the Checklist_ChecklistItems_Item as a SubChecklist
func (t Checklist_ChecklistItems_Item) AsSubChecklist() (SubChecklist, error) {
	var body SubChecklist
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklist overwrites any union data inside the Checklist_ChecklistItems_Item as the provided SubChecklist
func (t *Checklist_ChecklistItems_Item) FromSubChecklist(v SubChecklist) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklist performs a merge with any union data inside the Checklist_ChecklistItems_Item, using the provided SubChecklist
func (t *Checklist_ChecklistItems_Item) MergeSubChecklist(v SubChecklist) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSectionTitle returns the union data inside the Checklist_ChecklistItems_Item as a SectionTitle
func (t Checklist_ChecklistItems_Item) AsSectionTitle() (SectionTitle, error) {
	var body SectionTitle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSectionTitle overwrites any union data inside the Checklist_ChecklistItems_Item as the provided SectionTitle
func (t *Checklist_ChecklistItems_Item) FromSectionTitle(v SectionTitle) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSectionTitle performs a merge with any union data inside the Checklist_ChecklistItems_Item, using the provided SectionTitle
func (t *Checklist_ChecklistItems_Item) MergeSectionTitle(v SectionTitle) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextBox returns the union data inside the Checklist_ChecklistItems_Item as a TextBox
func (t Checklist_ChecklistItems_Item) AsTextBox() (TextBox, error) {
	var body TextBox
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextBox overwrites any union data inside the Checklist_ChecklistItems_Item as the provided TextBox
func (t *Checklist_ChecklistItems_Item) FromTextBox(v TextBox) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextBox performs a merge with any union data inside the Checklist_ChecklistItems_Item, using the provided TextBox
func (t *Checklist_ChecklistItems_Item) MergeTextBox(v TextBox) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Checklist_ChecklistItems_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Checklist_ChecklistItems_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSubChecklist returns the union data inside the ChecklistForm_ChecklistItems_Item as a SubChecklist
func (t ChecklistForm_ChecklistItems_Item) AsSubChecklist() (SubChecklist, error) {
	var body SubChecklist
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklist overwrites any union data inside the ChecklistForm_ChecklistItems_Item as the provided SubChecklist
func (t *ChecklistForm_ChecklistItems_Item) FromSubChecklist(v SubChecklist) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklist performs a merge with any union data inside the ChecklistForm_ChecklistItems_Item, using the provided SubChecklist
func (t *ChecklistForm_ChecklistItems_Item) MergeSubChecklist(v SubChecklist) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSectionTitle returns the union data inside the ChecklistForm_ChecklistItems_Item as a SectionTitle
func (t ChecklistForm_ChecklistItems_Item) AsSectionTitle() (SectionTitle, error) {
	var body SectionTitle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSectionTitle overwrites any union data inside the ChecklistForm_ChecklistItems_Item as the provided SectionTitle
func (t *ChecklistForm_ChecklistItems_Item) FromSectionTitle(v SectionTitle) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSectionTitle performs a merge with any union data inside the ChecklistForm_ChecklistItems_Item, using the provided SectionTitle
func (t *ChecklistForm_ChecklistItems_Item) MergeSectionTitle(v SectionTitle) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTextBox returns the union data inside the ChecklistForm_ChecklistItems_Item as a TextBox
func (t ChecklistForm_ChecklistItems_Item) AsTextBox() (TextBox, error) {
	var body TextBox
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTextBox overwrites any union data inside the ChecklistForm_ChecklistItems_Item as the provided TextBox
func (t *ChecklistForm_ChecklistItems_Item) FromTextBox(v TextBox) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTextBox performs a merge with any union data inside the ChecklistForm_ChecklistItems_Item, using the provided TextBox
func (t *ChecklistForm_ChecklistItems_Item) MergeTextBox(v TextBox) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ChecklistForm_ChecklistItems_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ChecklistForm_ChecklistItems_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSubChecklistItemCheckItem returns the union data inside the SubChecklist_Items_Item as a SubChecklistItemCheckItem
func (t SubChecklist_Items_Item) AsSubChecklistItemCheckItem() (SubChecklistItemCheckItem, error) {
	var body SubChecklistItemCheckItem
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemCheckItem overwrites any union data inside the SubChecklist_Items_Item as the provided SubChecklistItemCheckItem
func (t *SubChecklist_Items_Item) FromSubChecklistItemCheckItem(v SubChecklistItemCheckItem) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemCheckItem performs a merge with any union data inside the SubChecklist_Items_Item, using the provided SubChecklistItemCheckItem
func (t *SubChecklist_Items_Item) MergeSubChecklistItemCheckItem(v SubChecklistItemCheckItem) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemPrecondition returns the union data inside the SubChecklist_Items_Item as a SubChecklistItemPrecondition
func (t SubChecklist_Items_Item) AsSubChecklistItemPrecondition() (SubChecklistItemPrecondition, error) {
	var body SubChecklistItemPrecondition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemPrecondition overwrites any union data inside the SubChecklist_Items_Item as the provided SubChecklistItemPrecondition
func (t *SubChecklist_Items_Item) FromSubChecklistItemPrecondition(v SubChecklistItemPrecondition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemPrecondition performs a merge with any union data inside the SubChecklist_Items_Item, using the provided SubChecklistItemPrecondition
func (t *SubChecklist_Items_Item) MergeSubChecklistItemPrecondition(v SubChecklistItemPrecondition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemPostcondition returns the union data inside the SubChecklist_Items_Item as a SubChecklistItemPostcondition
func (t SubChecklist_Items_Item) AsSubChecklistItemPostcondition() (SubChecklistItemPostcondition, error) {
	var body SubChecklistItemPostcondition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemPostcondition overwrites any union data inside the SubChecklist_Items_Item as the provided SubChecklistItemPostcondition
func (t *SubChecklist_Items_Item) FromSubChecklistItemPostcondition(v SubChecklistItemPostcondition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemPostcondition performs a merge with any union data inside the SubChecklist_Items_Item, using the provided SubChecklistItemPostcondition
func (t *SubChecklist_Items_Item) MergeSubChecklistItemPostcondition(v SubChecklistItemPostcondition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemSubtitle returns the union data inside the SubChecklist_Items_Item as a SubChecklistItemSubtitle
func (t SubChecklist_Items_Item) AsSubChecklistItemSubtitle() (SubChecklistItemSubtitle, error) {
	var body SubChecklistItemSubtitle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemSubtitle overwrites any union data inside the SubChecklist_Items_Item as the provided SubChecklistItemSubtitle
func (t *SubChecklist_Items_Item) FromSubChecklistItemSubtitle(v SubChecklistItemSubtitle) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemSubtitle performs a merge with any union data inside the SubChecklist_Items_Item, using the provided SubChecklistItemSubtitle
func (t *SubChecklist_Items_Item) MergeSubChecklistItemSubtitle(v SubChecklistItemSubtitle) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SubChecklist_Items_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SubChecklist_Items_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSubChecklistItemCheckItem returns the union data inside the SubChecklistForm_Items_Item as a SubChecklistItemCheckItem
func (t SubChecklistForm_Items_Item) AsSubChecklistItemCheckItem() (SubChecklistItemCheckItem, error) {
	var body SubChecklistItemCheckItem
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemCheckItem overwrites any union data inside the SubChecklistForm_Items_Item as the provided SubChecklistItemCheckItem
func (t *SubChecklistForm_Items_Item) FromSubChecklistItemCheckItem(v SubChecklistItemCheckItem) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemCheckItem performs a merge with any union data inside the SubChecklistForm_Items_Item, using the provided SubChecklistItemCheckItem
func (t *SubChecklistForm_Items_Item) MergeSubChecklistItemCheckItem(v SubChecklistItemCheckItem) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemPrecondition returns the union data inside the SubChecklistForm_Items_Item as a SubChecklistItemPrecondition
func (t SubChecklistForm_Items_Item) AsSubChecklistItemPrecondition() (SubChecklistItemPrecondition, error) {
	var body SubChecklistItemPrecondition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemPrecondition overwrites any union data inside the SubChecklistForm_Items_Item as the provided SubChecklistItemPrecondition
func (t *SubChecklistForm_Items_Item) FromSubChecklistItemPrecondition(v SubChecklistItemPrecondition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemPrecondition performs a merge with any union data inside the SubChecklistForm_Items_Item, using the provided SubChecklistItemPrecondition
func (t *SubChecklistForm_Items_Item) MergeSubChecklistItemPrecondition(v SubChecklistItemPrecondition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemPostcondition returns the union data inside the SubChecklistForm_Items_Item as a SubChecklistItemPostcondition
func (t SubChecklistForm_Items_Item) AsSubChecklistItemPostcondition() (SubChecklistItemPostcondition, error) {
	var body SubChecklistItemPostcondition
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemPostcondition overwrites any union data inside the SubChecklistForm_Items_Item as the provided SubChecklistItemPostcondition
func (t *SubChecklistForm_Items_Item) FromSubChecklistItemPostcondition(v SubChecklistItemPostcondition) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemPostcondition performs a merge with any union data inside the SubChecklistForm_Items_Item, using the provided SubChecklistItemPostcondition
func (t *SubChecklistForm_Items_Item) MergeSubChecklistItemPostcondition(v SubChecklistItemPostcondition) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSubChecklistItemSubtitle returns the union data inside the SubChecklistForm_Items_Item as a SubChecklistItemSubtitle
func (t SubChecklistForm_Items_Item) AsSubChecklistItemSubtitle() (SubChecklistItemSubtitle, error) {
	var body SubChecklistItemSubtitle
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSubChecklistItemSubtitle overwrites any union data inside the SubChecklistForm_Items_Item as the provided SubChecklistItemSubtitle
func (t *SubChecklistForm_Items_Item) FromSubChecklistItemSubtitle(v SubChecklistItemSubtitle) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSubChecklistItemSubtitle performs a merge with any union data inside the SubChecklistForm_Items_Item, using the provided SubChecklistItemSubtitle
func (t *SubChecklistForm_Items_Item) MergeSubChecklistItemSubtitle(v SubChecklistItemSubtitle) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t SubChecklistForm_Items_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *SubChecklistForm_Items_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Returns a list of checklists
	// (GET /checklists)
	GetChecklists(w http.ResponseWriter, r *http.Request)
	// Creates a new checklist
	// (POST /checklists)
	PostChecklists(w http.ResponseWriter, r *http.Request)
	// Deletes a checklist
	// (DELETE /checklists/{id})
	DeleteChecklistsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Returns a single checklist
	// (GET /checklists/{id})
	GetChecklistsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Partially updates a checklist
	// (PATCH /checklists/{id})
	PatchChecklistsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Updates a checklist
	// (PUT /checklists/{id})
	PutChecklistsId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetChecklists operation middleware
func (siw *ServerInterfaceWrapper) GetChecklists(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChecklists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PostChecklists operation middleware
func (siw *ServerInterfaceWrapper) PostChecklists(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostChecklists(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// DeleteChecklistsId operation middleware
func (siw *ServerInterfaceWrapper) DeleteChecklistsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChecklistsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetChecklistsId operation middleware
func (siw *ServerInterfaceWrapper) GetChecklistsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChecklistsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PatchChecklistsId operation middleware
func (siw *ServerInterfaceWrapper) PatchChecklistsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchChecklistsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// PutChecklistsId operation middleware
func (siw *ServerInterfaceWrapper) PutChecklistsId(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutChecklistsId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       *http.ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m *http.ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m *http.ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/checklists", wrapper.GetChecklists)
	m.HandleFunc("POST "+options.BaseURL+"/checklists", wrapper.PostChecklists)
	m.HandleFunc("DELETE "+options.BaseURL+"/checklists/{id}", wrapper.DeleteChecklistsId)
	m.HandleFunc("GET "+options.BaseURL+"/checklists/{id}", wrapper.GetChecklistsId)
	m.HandleFunc("PATCH "+options.BaseURL+"/checklists/{id}", wrapper.PatchChecklistsId)
	m.HandleFunc("PUT "+options.BaseURL+"/checklists/{id}", wrapper.PutChecklistsId)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZTW/jNhD9K8K0Rzr27iYX3ZINtg26bYwmPS1yoKWxzY1EquQojWvovxekPqwPJ5at",
	"pPECuQSyyOEM35s3QyprCFScKImSDPhrMMESY+4eL5QOUd8uRXAv0bhXKNMY/G8T9oF9ZKd3DGiVIPgg",
	"03iGGhg8jhZqZF+OzL1IRiohoSSPRokSklCDTzrFjMHnJQb3kTBkV+VRdD0H/9saftY4Bx9+Gm+CGhcR",
	"jSuTL0rHkLE1JFolqEmgi02E9u9c6ZgT+JCmIoQqQENayEXvALPKUM2+Y0CQ3dWDdhH47QBmXbye208b",
	"3oxBUDq4IozzTZUPXK56YHSTzjbIWoienYyB3fytoAh3Tr7FR7pQjzkQBTZca77ag/RARWks3XaKFez4",
	"Yq/ECTRywibVIScckYjxYL4ZzJWkLzwW0aoW3kGr3Ih/cdAWJY9xSBAJX+C1FiiJ2xm78nDaml6sUG5j",
	"l6mblzEwtIp2GlTJeeNmZwzSJHwFPrv6ranXiuvWjVYFDRrCYdCQBoMy+Rl8dil8oZHfAwO7//z57vDM",
	"a2FSC+pSkQEGX4W0QfwuwuLFJTdLtMXtls8iHOJ72k2V0vlUadJcWDS+chmagCeDXZU5Vfo4PwUG52fW",
	"BRI5kfzKo3nxY4CzBn+9O0zd6s2aTCeITp/ZdIkXDMZVZ6WH1B3CRxpkX2iyVwGpRLxV6w059+e/ZvV2",
	"/LeD+GH4Fy9waLG0uh/2YfcJpmU51RgoGYqij+1prAwdbn2Tzig/SA04IFFZr45MQk1WDtJTY4mjEFc3",
	"oo7SeFB2xSGaGGJv6gG/qNz7pEobrv7Z0hTTwRnTWOZosqYbVSdzXpG3/6HLDuC9XoEPp722yvGw3g7q",
	"nfR27zuY8HKFoyG7EdA70U/cmjdnAgYN5TNoNgC3VJ4jA2515TW8d5oVBm+WVXX/79e4fc+g9pWQc2UX",
	"C9EEWiR5W9l8MhGP3vn0CqqT85aRB9Qmt/pwMjmZ2LRWCUqeCPDh08nk5BMwSDgtHSnjihX3c4EOCkub",
	"+0BiqYJfkD5vZjHQaBIlTc7qx8nEkaskoczvnkkSicCZj7+bvC3mODTuSr3ggvbdwoHUBOdcem7MU3Ov",
	"tpvMnSbjmOsV+PAnUqql8bhnR1tTGRBfmErg+Uubz4kyW/CwUm8B8neKhi5UuNoLiz2+/ne3XU3wbM5Y",
	"LeWFxwYjNIZVfrbo+rAlvYpvzBmD05zO5vgFD71ij3bO2bY5V1YTkkeeQf2A2kOtlW6RkPuxJEj8Z0PA",
	"U/hnrJ6e47UIs9xvhIRdWi7d+80KV6FLdM1jJNTGFU9hQ7XJD+VnZ3DFpwkaq3H0fJnKsrvtemiCc31v",
	"cfs4Oe0O/aG8Ml9eG/4cIAv/TuhZj0rwpvi+rMa26ev6t5yQrZyRN1epDAfRsSlJRshFhH1YSTgFyy0V",
	"yb5+E2Z+oML3pC5fVXRTrknwKFp5+X9+esovSbc1npTeST5Gkv/qT60zdCvllDWdXeIDRiqJUVLhDxik",
	"OgIflkSJ8cfjSAU8WipD/tlkcgaWocLRuuS85jC7y/4LAAD//+4LxeHyIAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
