syntax = "proto3";

import "google/protobuf/timestamp.proto";

option go_package = "github.com/braincompiler/checklistix/pkg/checklists/endpoints/grpc";

message Checklist {
    string id = 1;
    string title = 2;
    google.protobuf.Timestamp created = 3;
    google.protobuf.Timestamp updated = 4;
    string style = 5;
    string pageSize = 6;
    string pageOrientation = 7;
    int64 columns = 8;
    int64 fontSize = 9;
    int64 borderThickness = 10;
    string fontFamily = 11;
    string defaultColor = 12;
}

service ChecklistsGrpcService {
    rpc UpdateChecklist(Checklist) returns(Checklist) {}
}
